### ISSUE TITLE
This method is not supported by the current version of the framework and the current WebView APK

### ISSUE THREAD

**Issue by encyclist** [KevinnZou/compose-webview-multiplatform#156]
三星S8(安卓9)上测到崩溃：
``` java
java.lang.UnsupportedOperationException: This method is not supported by the current version of the framework and the current WebView APK
    at androidx.webkit.internal.WebViewFeatureInternal.getUnsupportedOperationException(WebViewFeatureInternal.java:680)
    at androidx.webkit.WebSettingsCompat.setForceDarkStrategy(WebSettingsCompat.java:546)
    at com.multiplatform.webview.web.AccompanistWebViewKt$AccompanistWebView$12.invoke(AccompanistWebView.kt:219)
    at com.multiplatform.webview.web.AccompanistWebViewKt$AccompanistWebView$12.invoke(AccompanistWebView.kt:161)
    at androidx.compose.ui.viewinterop.ViewFactoryHolder.<init>(AndroidView.android.kt:343)
    at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke(AndroidView.android.kt:274)
    at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke(AndroidView.android.kt:273)
```
安卓死丢丢提示：setForceDarkStrategy should only be called if the feature FORCE_DARK_STRATEGY is present; to check call androidx.webkit.WebViewFeature#isFeatureSupported

增加判断可解：
``` kotlin
if (WebViewFeature.isFeatureSupported(WebViewFeature.FORCE_DARK_STRATEGY)) { // 添加这一行
    WebSettingsCompat.setForceDarkStrategy(
        this.settings,
        WebSettingsCompat.DARK_STRATEGY_WEB_THEME_DARKENING_ONLY,
    )
}
```

**Comment by KevinnZou** [comment]
@encyclist Thanks for your suggestion! I have submitted a PR to fix it and plan to release it next week. Thanks again!
