### ISSUE TITLE
Local html files not loading in desktop

### ISSUE THREAD

**Issue by andreshl** [KevinnZou/compose-webview-multiplatform#187]
I ned load a local html file, in android it works bu in desktop i've the next error

java.lang.Object org.jetbrains.compose.resources.ResourceReader_desktopKt.readResourceBytes(java.lang.String, kotlin.coroutines.Continuation)

`Exception in thread "AWT-EventQueue-0 @coroutine#2213" java.lang.NoSuchMethodError: 'java.lang.Object org.jetbrains.compose.resources.ResourceReader_desktopKt.readResourceBytes(java.lang.String, kotlin.coroutines.Continuation)'
	at compose_webview_multiplatform.webview.generated.resources.Res.readBytes(Res.kt:24)
	at com.multiplatform.webview.web.WebView_desktopKt$DesktopWebView$fileContent$2.invokeSuspend(WebView.desktop.kt:66)
	at com.multiplatform.webview.web.WebView_desktopKt$DesktopWebView$fileContent$2.invoke(WebView.desktop.kt)
	at com.multiplatform.webview.web.WebView_desktopKt$DesktopWebView$fileContent$2.invoke(WebView.desktop.kt)
	at androidx.compose.runtime.SnapshotStateKt__ProduceStateKt$produceState$2.invokeSuspend(ProduceState.kt:116)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:99)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.scene.ComposeContainer$DesktopCoroutineExceptionHandler@18c2cca4, androidx.compose.runtime.BroadcastFrameClock@4d6081f8, CoroutineId(2213), "coroutine#2213":StandaloneCoroutine{Cancelling}@b672aa4, FlushCoroutineDispatcher@504a69c4]
Exception in thread "Thread-9" java.lang.ClassNotFoundException: org.cef.CefBrowserSettings
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
Info: (ComposeWebView) Failed to load url: ERR_FILE_NOT_FOUND file:///kcefbrowser/556144442#url=about:blank
ERR_FILE_NOT_FOUND
[0701/122714.586:ERROR:interface_endpoint_client.cc(707)] Message 3 rejected by interface blink.mojom.Widget
`

i put my file in common resources

![image](https://github.com/KevinnZou/compose-webview-multiplatform/assets/17575329/f148eac3-6d8e-4efd-8de1-a84002e2f363)

**Comment by KevinnZou** [comment]
@andreshl What's your CMP and Kotlin version?

**Comment by andreshl** [comment]
> @andreshl What's your CMP and Kotlin version?

Is the kmp 2.0 compose i think Is the same

**Comment by andreshl** [comment]
updating
maybe the compose.components plugin has  some problems
compose-plugin = "1.6.11"

**Comment by andreshl** [comment]
yes the resource api, kotlin removes the resource method and the resources way to read is different can you helpme with that XD

**Comment by KevinnZou** [comment]
@andreshl Which version of this library are you using? Please upgrade to the latest version and it should work.

**Comment by Jacko760** [comment]
I am encountering an issue while trying to load an HTML file into a WebView using the compose-webview-multiplatform library. The WebView fails to load the resource and throws an exception. Below is the setup and the error:

Environment:

	•	AGP: 8.2.2
	•	Kotlin: 2.0.20
	•	Compose Plugin: 1.6.11
	•	Library Version: io.github.kevinnzou:compose-webview-multiplatform:1.9.20

Code Snippet:

val webViewState = rememberWebViewStateWithHTMLFile(fileName = "index.html")
Column(Modifier.fillMaxSize()) {
    WebView(
        state = webViewState,
        modifier = Modifier.fillMaxSize()
    )
}

Error Log:

java.lang.Object org.jetbrains.compose.resources.ResourceReader_desktopKt.readResourceBytes(java.lang.String, kotlin.coroutines.Continuation)'

Steps to Reproduce:

	1.	Use the above setup to try and load a simple HTML file into the WebView.
	2.	Run the app (targeting desktop).
	3.	The WebView fails to load, and the above error is thrown.


Expected Behavior:

The WebView should load the HTML file (index.html) without issues.

Actual Behavior:

The app throws the mentioned exception and the WebView remains blank.

Additional Information:

	•	I have already confirmed that the index.html file is correctly placed in the resources directory and can be accessed elsewhere in the app.
	•	This issue occurs on the desktop platform.
	•	The same setup works for other platforms (if applicable).

Any help or guidance on resolving this issue would be appreciated.

NOTE :
The WebView works fine when embedding the HTML directly inside a Kotlin class, but it fails when trying to load the same HTML from a 
![5b475194-8893-4706-b75b-8389367390b2](https://github.com/user-attachments/assets/1d5db7e0-0c3c-4431-9af8-71e6eac54547)
![389d8c16-e4bd-49db-88e5-26c97ae54104](https://github.com/user-attachments/assets/4fb6f253-65a3-48e5-863d-72eb8a7f0e98)
![5b475194-8893-4706-b75b-8389367390b2](https://github.com/user-attachments/assets/36ee47b4-0170-45df-a980-78146fdabdbd)
![389d8c16-e4bd-49db-88e5-26c97ae54104](https://github.com/user-attachments/assets/e44055b9-8831-46ef-843b-4bd14a034c40)
file

**Comment by Jacko760** [comment]
> Am I missing something or is this not implemented? The desktop override does nothing? `override suspend fun loadHtmlFile(fileName: String) { // TODO }`
> 
> https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/webview/src/desktopMain/kotlin/com/multiplatform/webview/web/DesktopWebView.kt#L70

have you found any solution o r issues are still logged ?
