### ISSUE TITLE
Desktop Platform Incompaitible with Ktor 3.0.0

### ISSUE THREAD

**Issue by LOOHP** [KevinnZou/compose-webview-multiplatform#244]
The desktop version of this library seems to be using an old version of Ktor and is incompatible with the binaries of Ktor 3.0.0. Could the Ktor version be updated?

Here's the error in question:
```
java.lang.NoClassDefFoundError: io/ktor/client/plugins/HttpTimeout
	at io.ktor.client.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:40)
	at io.ktor.client.engine.okhttp.OkHttp.create(OkHttp.kt:31)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:43)
	at dev.datlag.kcef.step.fetch.PackageDownloader.downloadPackage(PackageDownloader.kt:37)
	at dev.datlag.kcef.KCEFBuilder.install$kcef(KCEFBuilder.kt:196)
	at dev.datlag.kcef.KCEF$init$installResult$1.invokeSuspend(KCEF.kt:105)
	at dev.datlag.kcef.KCEF$init$installResult$1.invoke(KCEF.kt)
	at dev.datlag.kcef.KCEF$init$installResult$1.invoke(KCEF.kt)
	at dev.datlag.kcef.common.ExtendCoroutineKt$suspendCatching$2.invokeSuspend(ExtendCoroutine.kt:19)
	at dev.datlag.kcef.common.ExtendCoroutineKt$suspendCatching$2.invoke(ExtendCoroutine.kt)
	at dev.datlag.kcef.common.ExtendCoroutineKt$suspendCatching$2.invoke(ExtendCoroutine.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at dev.datlag.kcef.common.ExtendCoroutineKt.suspendCatching(ExtendCoroutine.kt:16)
	at dev.datlag.kcef.KCEF.init(KCEF.kt:104)
	at dev.datlag.kcef.KCEF.init(KCEF.kt:45)
	at com.loohp.hkbuseta.app.MapInterface_desktopKt$KCEFWebContainer$1$1$1.invokeSuspend(MapInterface.desktop.kt:104)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.HttpTimeout
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more
java.lang.NoClassDefFoundError: io/ktor/client/plugins/HttpTimeout
	at io.ktor.client.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:40)
	at io.ktor.client.engine.okhttp.OkHttp.create(OkHttp.kt:31)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:43)
	at dev.datlag.kcef.step.fetch.PackageDownloader.downloadPackage(PackageDownloader.kt:37)
	at dev.datlag.kcef.KCEFBuilder.install$kcef(KCEFBuilder.kt:196)
	at dev.datlag.kcef.KCEFBuilder.build$kcef(KCEFBuilder.kt:241)
	at dev.datlag.kcef.KCEF$init$result$2.invokeSuspend(KCEF.kt:113)
	at dev.datlag.kcef.KCEF$init$result$2.invoke(KCEF.kt)
	at dev.datlag.kcef.KCEF$init$result$2.invoke(KCEF.kt)
	at dev.datlag.kcef.common.ExtendCoroutineKt$suspendCatching$2.invokeSuspend(ExtendCoroutine.kt:19)
	at dev.datlag.kcef.common.ExtendCoroutineKt$suspendCatching$2.invoke(ExtendCoroutine.kt)
	at dev.datlag.kcef.common.ExtendCoroutineKt$suspendCatching$2.invoke(ExtendCoroutine.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at dev.datlag.kcef.common.ExtendCoroutineKt.suspendCatching(ExtendCoroutine.kt:16)
	at dev.datlag.kcef.KCEF.init(KCEF.kt:112)
	at dev.datlag.kcef.KCEF.init(KCEF.kt:45)
	at com.loohp.hkbuseta.app.MapInterface_desktopKt$KCEFWebContainer$1$1$1.invokeSuspend(MapInterface.desktop.kt:104)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.HttpTimeout
	... 26 more
Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.HttpTimeout
```

**Comment by LOOHP** [comment]
Fixed in fa9e47a with the release of `1.9.40-alpha04`
