### ISSUE TITLE
not working on release build

### ISSUE THREAD

**Issue by rdelacosta** [KevinnZou/compose-webview-multiplatform#27]
in my windows desktop app, I have no problem making it work for non-release build. However when I'm running using release build I am experiencing an error

I have included modules in build.gradle.kts (includeAllModules = true) as well as followed this readme https://github.com/KevinnZou/compose-webview-multiplatform/blob/main/README.desktop.md

**_[createContext(...) must not be null]_** error shows

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassNotFoundException: org.cef.callback.CefCommandLine_N
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.cef.CefApp.N_Initialize(Native Method)
	at org.cef.CefApp.access$400(CefApp.java:25)
	at org.cef.CefApp$3.run(CefApp.java:427)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: onBeforeCommandLineProcessing
	at org.cef.CefApp.N_Initialize(Native Method)
	at org.cef.CefApp.access$400(CefApp.java:25)
	at org.cef.CefApp$3.run(CefApp.java:427)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ClassNotFoundException: org.cef.callback.CefSchemeRegistrar_N
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.cef.CefApp.N_Initialize(Native Method)
	at org.cef.CefApp.access$400(CefApp.java:25)
	at org.cef.CefApp$3.run(CefApp.java:427)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: onRegisterCustomSchemes
	at org.cef.CefApp.N_Initialize(Native Method)
	at org.cef.CefApp.access$400(CefApp.java:25)
	at org.cef.CefApp$3.run(CefApp.java:427)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "Thread-5" java.lang.NoSuchMethodError: onContextInitialized
Exception in thread "DefaultDispatcher-worker-1" java.lang.NoSuchMethodError: getNativeRef
	at org.cef.handler.CefClientHandler.N_CefClientHandler_CTOR(Native Method)
	at org.cef.handler.CefClientHandler.<init>(CefClientHandler.java:39)
	at org.cef.CefClient.<init>(CefClient.java:110)
	at org.cef.CefApp.createClient(CefApp.java:320)
	at com.multiplatform.webview.web.Cef.newClient(Cef.kt:98)
	at com.multiplatform.webview.web.Cef.newClient$default$4bfbdff3(Cef.kt:93)
	at com.multiplatform.webview.web.WebView_desktopKt$DesktopWebView$client$2$1.invokeSuspend(WebView.desktop.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1793)
Exception in thread "DefaultDispatcher-worker-1" java.lang.NoSuchMethodError: setNativeRef
	at org.cef.handler.CefClientHandler.N_CefClientHandler_CTOR(Native Method)
	at org.cef.handler.CefClientHandler.<init>(CefClientHandler.java:39)
	at org.cef.CefClient.<init>(CefClient.java:110)
	at org.cef.CefApp.createClient(CefApp.java:320)
	at com.multiplatform.webview.web.Cef.newClient(Cef.kt:98)
	at com.multiplatform.webview.web.Cef.newClient$default$4bfbdff3(Cef.kt:93)
	at com.multiplatform.webview.web.WebView_desktopKt$DesktopWebView$client$2$1.invokeSuspend(WebView.desktop.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1793)
java.lang.UnsatisfiedLinkError: 'org.cef.browser.CefMessageRouter$CefMessageRouterConfig org.cef.browser.CefMessageRouter$CefMessageRouterConfig.N_CreateContext$106d6c7e(org.cef.handler.CefRequestContextHandler)'
	at org.cef.browser.CefMessageRouter$CefMessageRouterConfig.N_CreateContext$106d6c7e(Native Method)
	at org.cef.browser.CefMessageRouter$CefMessageRouterConfig.createNative$106d6c7e(CefMessageRouter.java:1049)
	at org.cef.browser.CefMessageRouter$CefMessageRouterConfig.createContext$7f59e2ed(CefMessageRouter.java:1039)
	at com.multiplatform.webview.web.CefRequestExtKt.createModifiedRequestContext$140d9ba5(CefRequestExt.kt:29)
	at com.multiplatform.webview.web.WebView_desktopKt.DesktopWebView(WebView.desktop.kt:65)
	at com.multiplatform.webview.web.WebView_desktopKt$DesktopWebView$3.invoke(WebView.desktop.kt:1000)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2469)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2761)
.....
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: createContext(...) must not be null
	at com.multiplatform.webview.web.CefRequestExtKt.createModifiedRequestContext$140d9ba5(CefRequestExt.kt:29)
	at com.multiplatform.webview.web.WebView_desktopKt.DesktopWebView(WebView.desktop.kt:65)
	at com.multiplatform.webview.web.WebView_desktopKt$DesktopWebView$3.invoke(WebView.desktop.kt:1000)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2469)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2761)
```

**Comment by KevinnZou** [comment]
@DatL4g Could you have a look at it?

**Comment by KevinnZou** [comment]
@DatL4g Are there any updates?

**Comment by DatL4g** [comment]
Sorry I have no time to deeply look into it currently.

Please try to add this to the `build.gradle.kts` configuration:

```kotlin
compose {
	desktop {
		jvmArgs("--add-opens", "java.desktop/sun.awt=ALL-UNNAMED")
		jvmArgs("--add-opens", "java.desktop/java.awt.peer=ALL-UNNAMED")
		
		// create  method to check wether the current host you are building on is macOS
		if (host == Host.MacOS) {
			jvmArgs("--add-opens", "java.desktop/sun.lwawt=ALL-UNNAMED")
			jvmArgs("--add-opens", "java.desktop/sun.lwawt.macosx=ALL-UNNAMED")
		}
	}
}
```

These are all packages that may not be packaged or accessable when building against JDK 17 or up.
If the same error occurs, the `jcefmaven` package isn't configured properly.

**Comment by rdelacosta** [comment]
@DatL4g  thanks for your input. it seems that the issue was Proguard excluding classes in release build. I added the following in my proguard rules to whitelist these classes

```
-keep class org.cef.** {
    *;
}
```

Now, webview is displayed using release build but an error also immediately shows:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:115)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:96)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:319)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default$6a2188af(Cancellable.kt:25)
	at kotlinx.coroutines.BuildersKt__BuildersKt.withContext(Builders.kt:1172)
	at kotlinx.coroutines.CancellableContinuation$DefaultImpls.withContext(CancellableContinuation.kt:6001)
	at com.multiplatform.webview.web.WebViewNavigator.handleNavigationEvents$webview(WebViewNavigator.kt:119)
	at com.multiplatform.webview.web.WebViewKt$WebView$3$1.invokeSuspend(WebView.kt:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:1062)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:91)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@52226035, androidx.compose.runtime.BroadcastFrameClock@693d4488, StandaloneCoroutine{Cancelling}@f662beb, FlushCoroutineDispatcher@12e1dacd]
Caused by: java.util.ServiceConfigurationError: kotlinx.coroutines.internal.MainDispatcherFactory: Provider kotlinx.coroutines.swing.SwingDispatcherFactory not found
	at java.base/java.util.ServiceLoader.fail(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1295)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1328)
Caused by: java.util.ServiceConfigurationError: kotlinx.coroutines.internal.MainDispatcherFactory: Provider kotlinx.coroutines.swing.SwingDispatcherFactory not found

	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1319)
	at kotlinx.coroutines.internal.FastServiceLoader.load(FastServiceLoader.kt:90)
	at kotlinx.coroutines.internal.FastServiceLoader.loadMainDispatcherFactory$kotlinx_coroutines_core(FastServiceLoader.kt:55)
	at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:27)
	at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:22)
	at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:24)
```

Please feel free to provide any input if this error is within the scope of the library

**Comment by KevinnZou** [comment]
@rdelacosta I found a similar error in this [issue](https://github.com/JetBrains/compose-multiplatform/issues/3047), which appears to be caused by ProGuard.
Please try to add `-keep class kotlinx.coroutines.swing.SwingDispatcherFactory` to ProGuard rules.

**Comment by rdelacosta** [comment]
@KevinnZou @DatL4g 
thanks for your input. fixed by adding the following in proguard:

```
-keep class org.cef.** { *; }
-keep class kotlinx.coroutines.swing.SwingDispatcherFactory
```

**Comment by KevinnZou** [comment]
> @KevinnZou @DatL4g thanks for your input. fixed by adding the following in proguard:
> 
> ```
> -keep class org.cef.** { *; }
> -keep class kotlinx.coroutines.swing.SwingDispatcherFactory
> ```

@DatL4g It seems that incorrect ProGuard configuration can cause errors in the Desktop release build. Could you please add instructions on which classes from our library need to be retained in ProGuard to the README.desktop.md file, whenever you have time?
